### ISSUE TITLE
[Bug] Item models always load as empty mesh with version 1.6.0

### ISSUE THREAD

**Issue by Mondanzo** [Haven-King/myron#2]
When trying to load an item model using the way described [here](https://github.com/Haven-King/myron/wiki/Creating-Item-Models) the model can't get rendered and Myron throws an error saying "Mesh is null while emitting block quads for item". Using the same way on 1.5.2 works tho and the model gets rendered.

**Comment by jardhu** [comment]
Pull #3 fixes this ;]
